version: '3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./docker/data/db/mysql:/var/lib/mysql"
      - "./docker/etc/mysql:/etc/mysql/conf.d"
    networks:
      - vm-service

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    restart: always
    links:
      - database:db
    depends_on:
      - database
    networks:
      - vm-service

  php:
    build:
      context: ./docker/etc/php
      args:
        - INSTALL_NODE=${INSTALL_NODE}
        - INSTALL_GULP=${INSTALL_GULP}
        - INSTALL_BOWER=${INSTALL_BOWER}
        - INSTALL_POSTGRESQL=${INSTALL_POSTGRESQL}
        - INSTALL_MYSQL=${INSTALL_MYSQL}
        - INSTALL_GD=${INSTALL_GD}
        - ADD_ALIASES=${ADD_ALIASES}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    container_name: php
    ports:
      - "9000:9000"
    entrypoint: sh /bin/entrypoint.sh php-fpm
    links:
      - database:db
    restart: always
    volumes:
      - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${APP_PATH}:/var/www/html
      - "./docker/etc/log/nginx:/var/log/nginx"
      - ./docker/etc/php/entrypoint.sh:/bin/entrypoint.sh
    networks:
      - vm-service

  web:
    image: nginx:stable-alpine
    build: ./docker/etc/nginx
    container_name: nginx
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/etc/nginx/app.conf:/etc/nginx/sites-available/application.conf"
      - "./docker/etc/nginx/app.conf:/etc/nginx/sites-enabled/application"
      - "./docker/etc/ssl:/etc/ssl"
      - "./docker/etc/log/nginx:/var/log/nginx"
      - ${APP_PATH}:/var/www/html
    links:
      - php
      - database
    depends_on:
      - php
      - database
    networks:
      - vm-service

networks:
  vm-service:
      driver: bridge
