version: '3'
services:
  database:
    image: mysql:5.7
    container_name: ${APP_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PORT_DATABASE}:3306
    volumes:
      - "./docker/data/db/mysql:/var/lib/mysql"
      - "./docker/etc/mysql:/etc/mysql/conf.d"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - ${PORT_PHPMYADMIN}:80
    restart: always
    links:
      - database:db
    depends_on:
      - database
  php:
    build:
      context: ./docker/etc/php
      args:
        - INSTALL_NODE=${INSTALL_NODE}
        - INSTALL_GULP=${INSTALL_GULP}
        - INSTALL_BOWER=${INSTALL_BOWER}
        - INSTALL_POSTGRESQL=${INSTALL_POSTGRESQL}
        - INSTALL_MYSQL=${INSTALL_MYSQL}
        - INSTALL_GD=${INSTALL_GD}
        - ADD_ALIASES=${ADD_ALIASES}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    container_name: ${APP_NAME}_php
    entrypoint: sh /bin/entrypoint.sh php-fpm
    links:
      - database:mysqldb
    restart: always
    volumes:
      - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ${APP_PATH}:/var/www/html
      - './docker/etc/log/nginx:/var/log/nginx'
      - ./docker/etc/php/entrypoint.sh:/bin/entrypoint.sh
  web:
    build: ./docker/etc/nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - ${PORT_HTTP}:80
      - ${PORT_HTTPS}:443
    restart: always
    volumes:
      - "./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/etc/nginx/app.conf:/etc/nginx/sites-available/application.conf"
      - "./docker/etc/nginx/app.conf:/etc/nginx/sites-enabled/application"
      - "./docker/etc/ssl:/etc/ssl"
      - './docker/etc/log/nginx:/var/log/nginx'
      - ${APP_PATH}:/var/www/html
    depends_on:
      - php
      - database
